---
title: "PCA_view"
output: html_notebook
---
### Adapted Jan 2020 from a script by Bruno de Medeiros
### updated Jan 2021


installations

```{r}
library(stringr)
library(tidyverse)
library(readxl)
library(cowplot)
```


load files, data, varriables 

```{r}
#read data files
var.hives = readxl::read_excel('../../../varroa_project.xlsx', sheet = 'hives')
var.ext = readxl::read_excel('../../../varroa_project.xlsx', sheet = 'extractions')
var.api = readxl::read_excel('../../../varroa_project.xlsx', sheet = 'locations')
var.dig = readxl::read_excel('../../../varroa_project.xlsx', sheet = 'digest+ligation', range = "A1:C379")

covrs = read.delim('varroa.pca.cov', header = F, sep = ' ')
bamlist = read.delim('bam.filelist', header = F)
```

```{r}
#manipulate files 

#extract sample names
sample_id = substr(as.vector(t(bamlist)), 10, 15)
names = as.data.frame(sample_id)

#merge all varroa data into one df
var.data = merge(var.ext, var.hives, by = "hive_id") %>%
  merge(var.api, by = "apiary_id") %>% 
  separate(gps, c("lat","lon"), sep = ",") %>%
  merge(var.dig, by = "sample_id") %>%
  select(sample_id, apiary_id, hive_id, lat, lon, movement, type, region, 
         treatment, pool_id, date_collected, date_extracted)

#clean up tmp data sets
rm ( var.api, var.dig, var.ext, var.hives)

#order var.data to match bamlist 
var.data = var.data[match(sample_id, var.data$sample_id),]

#apply sample names
colnames(covrs) <- sample_id
rownames(covrs) <- t(sample_id)

#simple regions 
var.data = var.data %>% mutate(s_region = sub("-.*", "", region))

#simple type: resident samples considered as migratory for analysis

```


calculate eigenvalues and eigenvectors

```{r}
#eigenvalues
eig = eigen(covrs, symmetric = T)


#df for PCA plot
#script by Bruno
PCA_axes = eig$vectors[,1:2] %>%
  as.data.frame %>%
  rename(PC1 = 1, PC2 = 2) %>%
  mutate(PC1 = PC1 * sqrt(eig$values[1]),
         PC2 = PC2 * sqrt(eig$values[2]))

#variance captured by first 5 PC's
variance = eig$values/sum(eig$values)
variance[1:5]
```
concatenate

```{r}
var.data = cbind(var.data, PCA_axes)
```


###linear models

by region
```{r}
region_df = data.frame(PC1 = PCA_axes$PC1, region = var.data$region)
#set reference to N.CA
region_df <- within(region_df, region <- relevel(region, ref = "CA-N")) 

region_model = lm(PC1 ~ region, data = region_df)
summary(region_model)
```

by apiary
```{r}
apiary_df = data.frame(PC1 = PCA_axes$PC1, apiary = var.data$apiary)

#set reference to largest N.CA apiary: API007
apiary_df <- within(apiary_df, apiary <- relevel(apiary, ref = "API007")) 

apiary_model = lm(PC1 ~ apiary, data = apiary_df)
summary(apiary_model)
```

by type
```{r}
type_df = data.frame(PC1 = PCA_axes$PC1, type = var.data$type)

#set reference to N.CA
type_df <- within(type_df, type <- relevel(type, ref = "c")) 

type_model = lm(PC1 ~ type, data = type_df)
summary(type_model)
```



###PCA plotting

```{r}
p.new = ggplot(var.data) +
  geom_point(aes(x = PC1, y = PC2, fill = s_region, shape = type), size = 3) +
  #scale_alpha_manual(guide= 'none', values = c(0.3, 1)) +
  theme(panel.border = element_rect(color='black',fill=NA),
        legend.direction = "horizontal") +

  scale_fill_viridis_d(name  = "Region",
                      breaks=c("CA", "OR", "WA","MT" ),
                      labels=c("California", "Oregon", "Washington", "Montana")) +
  
  guides(fill = guide_legend(override.aes=list(shape=21))) +

  scale_shape_manual(name = "Type",
                       values = c(24,21,23),
                       breaks = c("c","m","s"),
                       labels = c("Resident","Migratory","Sedentary")) 
  
  #geom_text(aes(x=PCA_axes$PC1, y=PCA_axes$PC2, label=var.data$sample_id),hjust=0.5, vjust=0)

print(p.new)
```

save to file
```{r}
ggsave(filename = "pca.pdf", plot = p.new, height = 5, width = 7)
```

```{r}
load("../../figures/map/map.Rdata")
load("../../figures/map/cutout.Rdata")
```


plot all in one 
```{r}
le = get_legend(p.new + theme(legend.box.margin = margin(0, 0, 0, 12)))
le2 = plot_grid(NULL, p_big, NULL, le, ncol = 4, nrow = 1, rel_widths = c(.2, 1, 1, .2))

p_out = plot_grid(p, 
          p.new + theme(legend.position = "none"),
          le2, 
          rel_heights = c(1, .3))

p_out
```

```{r}
ggsave(filename = "pcamap.pdf", plot = p_out, height = 5, width = 8.5)
```




### old work from first run
kept in case it can be reused


```{r eval=FALSE}
load("pold.Rdata")
```


```{r eval=FALSE}

ggarrange(p.old, p.new,
          labels = c("A","B"),
          ncol = 2, nrow = 1)

```



combine into one df
```{r eval=FALSE}
pca = cbind(ordered_info, PCA_axes) %>% as.data.frame()
pca.sed = pca %>% filter(type == "s")
pca.mig = pca %>% filter(type != "s")
```




```{r eval=FALSE}
#violin plots
v.type = ggplot(pca) + geom_violin(aes(x=type, y=PC1, color = type)) +
  scale_x_discrete(labels = c("Resident", "Migratory", "Sedentary"), breaks = c("c", "m", "s")) +
  xlab("Hive Movement") +
  ylab("PC 1") +
  theme(legend.position="none") +
  geom_jitter(aes(x=type, y=PC1), position = position_jitter(h=0, w=0.05), size = 1) 

v.region = ggplot(pca) + geom_violin(aes(x=region, y=PC1, color = region)) +
  ylab("PC 1") +
  theme(legend.position="none") +
  geom_jitter(aes(x=region, y=PC1), position = position_jitter(h=0, w=0.05), size = 1) +
      scale_x_discrete(name  = "Region: All Samples",
                      breaks=c("CA-B", "CA-N","OR-C", "OR-MWV","OR-P","WA-PS","MT-W", "MA"),
                      labels=c("CA-B", "CA-N", "OR-C", "OR-V","OR-P","WA-S","MT-W", "MA"))

v.reg.sed = ggplot(pca.sed) + geom_violin(aes(x=region, y=PC1, color = region)) +
  #scale_x_discrete(labels = c("Resident", "Migratory", "Sedentary"), breaks = c("c", "m", "s")) +
  xlab("Region: Sedentary") +
  ylab("PC 1") +
  theme(legend.position="none") +
  geom_jitter(aes(x=region, y=PC1), position = position_jitter(h=0, w=0.05), size = 1) +
      scale_x_discrete(name  = "Region: Sedentary",
                      breaks=c("CA-B", "OR-C", "OR-MWV","OR-P","WA-PS","MT-W", "MA"),
                      labels=c("CA-B", "OR-C", "OR-V","OR-P","WA-S","MT-W", "MA"))

v.pool = ggplot(pca) + geom_violin(aes(x=pool, y=PC1, color = pool)) +
  #scale_x_discrete(labels = c("Resident", "Migratory", "Sedentary"), breaks = c("c", "m", "s")) +
  xlab("Pools") +
  ylab("PC 1") +
  theme(legend.position="none") +
  geom_jitter(aes(x=pool, y=PC1), position = position_jitter(h=0, w=0.05), size = 1)

v.apiary = ggplot(pca) + geom_violin(aes(x=apiary_id, y=PC1, color = apiary_id)) +
  #scale_x_discrete(labels = c("Resident", "Migratory", "Sedentary"), breaks = c("c", "m", "s")) +
  xlab("Apiaries") +
  ylab("PC 1") +
  theme(legend.position="none") +
  geom_jitter(aes(x=apiary_id, y=PC1), position = position_jitter(h=0, w=0.04))
  
plot(v.type)
plot(v.region)
plot(v.reg.sed)
plot(v.pool)
```

```{r eval=FALSE}
ggarrange(v.pool, v.type, v.region, v.reg.sed,
          labels = c("A", "B", "C", "D"),
          ncol = 2, nrow = 2)
```



```{r eval=FALSE}
#plot by geographic distance
PC1 = PCA_axes$PC1
geo_info = cbind(geo_info, PC1)

#pc_dist = dist(geo_info$PC1)
#geo_dist = dist(geo_info[c("lat","lon")])
#plot(geo_dist, pc_dist)

#sedentary only
sedentary = geo_info %>% filter(region != "MA", type == "s")
geo_dist_s = dist(sedentary[c('lat','lon')])
pc_dist_s = dist(sedentary$PC1)

#migratory only
migratory = geo_info %>% filter(type != "s")
pc_dist_m = dist(migratory$PC1)
geo_dist_m = dist(migratory[c("lat","lon")])
plot(geo_dist_m, pc_dist_m)

```



```{r eval=FALSE}
#compare island to mainland
island = (ordered_info$apiary_id == "API022" | ordered_info$apiary_id == "API023")
ggplot(PCA_axes) + geom_violin(aes(x=island, y=PCA_axes$PC1))

#compare MA to everything else
ggplot(PCA_axes) + geom_violin(aes(x=(ordered_info$region == "MA"), y=PCA_axes$PC1))

```


```{r eval=FALSE}
#sedentary only by region
pc_sed = PCA_axes[(ordered_info$type == "s"),]
ggplot(pc_sed) + geom_violin(aes(x=sedentary$region, y=pc_sed$PC1))
```


```{r eval=FALSE}
#mantel test
#install.packages("ape")
library(ape)
#all samples
mantel.test(as.matrix(pc_dist), as.matrix(geo_dist), nperm = 500, graph = TRUE, alternative = "greater")

#sedentary only
mantel.test(as.matrix(pc_dist_s), as.matrix(geo_dist_s), nperm = 500, graph = TRUE, alternative = "greater")

#migratory only
mantel.test(as.matrix(pc_dist_m), as.matrix(geo_dist_m), nperm = 500, graph = TRUE, alternative = "greater")
```



